import { isAttackPackageEvent } from "./packages";
import type {
  AimedSpreadEvent,
  AttackEvent,
  AttackPackageEvent,
  BossMirroredFanEvent,
  BulletMotionFields,
  BulletPattern,
  CurvedLaserRingEvent,
  FireClipFields,
  LaserBeamEvent,
  MovingBlockEvent,
  PolynomialProjectileEvent,
  RadialBurstEvent,
  RotatingShapeEvent,
  SpawnCurvedLaserEvent,
  SpawnRadialEvent,
  StageSize,
} from "./types";

interface Float2 {
  x: number;
  y: number;
}

interface Float4 {
  x: number;
  y: number;
  z: number;
  w: number;
}

export interface UnityMusicEventJson {
  barCount: number;
  BPM: number;
  beatTimings: number[];
  measure: number;
  barStartOffsetBeats: number;
}

export interface UnityBulletSpawnerJson {
  clipName: string;
  count: number;
  interval: number;
  time: number;
  pos: Float2;
  originVlc: Float2;
  angle: number;
  angleInterval: number;
  color: Float4;
  speed: number;
  size: number;
  laserCount: number;
  laserSpacing: number;
  laserLength: number;
  laserWidth: number;
}

export interface UnityStageDataJson {
  stageName: string;
  MusicEvents: UnityMusicEventJson[];
  delayTime: number;
  stageDescription: string;
  enemySpawners: unknown[];
  bulletSpawners: UnityBulletSpawnerJson[];
}

export interface UnityBulletDataJson {
  position: Float2;
  velocity: Float2;
  angle: number;
  originPos: Float2;
  originVlc: Float2;
  startX: number;
  speed: number;
  accel: number;
  acccel: number;
  gravity: number;
  angleSpeed: number;
  polarForm: Float2;
  radiusVlc: number;
  thetaVlc: number;
  startPos: Float2;
  nowCalculateVlc: Float2;
  nowCalculateX: number;
  polynomial: Float4;
  typeId: number;
  typeName: string;
  size: number;
  color: Float4;
  areaNum: number;
  time: number;
  appearTime: number;
  life: number;
  random: number;
  isActive: boolean;
}

export interface UnityBulletBufferJson {
  name: string;
  bullets: UnityBulletDataJson[];
  homing: boolean;
  isLaser: boolean;
}

export interface UnityBulletBufferCollectionJson {
  format: "BulletBufferCollection";
  bulletBuffers: UnityBulletBufferJson[];
}

export interface UnitySeparatedExport {
  stageData: UnityStageDataJson;
  bulletBufferCollection: UnityBulletBufferCollectionJson;
  skippedEvents: Array<{ id: string; name: string; kind: string; reason: string }>;
}

const unityWorldWidth = 18;
const unityWorldHeight = 36;
const unityLaserOverscanMultiplier = 1.25;
const polynomialUnitPixels = 100;

export function buildUnitySeparatedExport(pattern: BulletPattern): UnitySeparatedExport {
  const context: ExportContext = {
    pattern,
    scaleX: pattern.stage.width / unityWorldWidth,
    scaleY: pattern.stage.height / unityWorldHeight,
    buffers: [],
    spawners: [],
    skippedEvents: [],
    usedNames: new Set<string>(),
  };

  for (const event of getUnityExportEvents(pattern.events)) {
    exportEvent(context, event);
  }

  return {
    stageData: {
      stageName: pattern.title || "Stage",
      MusicEvents: [
        {
          barCount: Math.max(1, Math.ceil(pattern.duration / getMeasureDuration(pattern))),
          BPM: pattern.timeline.bpm,
          beatTimings: Array.from({ length: Math.max(1, Math.round(pattern.timeline.beatsPerMeasure)) }, (_, index) => index),
          measure: Math.max(1, Math.round(pattern.timeline.beatsPerMeasure)),
          barStartOffsetBeats: 0,
        },
      ],
      delayTime: pattern.timeline.musicOffset,
      stageDescription: "Generated by 弾幕メーカー",
      enemySpawners: [],
      bulletSpawners: context.spawners.sort((a, b) => a.time - b.time),
    },
    bulletBufferCollection: {
      format: "BulletBufferCollection",
      bulletBuffers: context.buffers,
    },
    skippedEvents: context.skippedEvents,
  };
}

interface ExportContext {
  pattern: BulletPattern;
  scaleX: number;
  scaleY: number;
  buffers: UnityBulletBufferJson[];
  spawners: UnityBulletSpawnerJson[];
  skippedEvents: UnitySeparatedExport["skippedEvents"];
  usedNames: Set<string>;
}

function getUnityExportEvents(events: AttackEvent[]): AttackEvent[] {
  return events.filter((event) => !isAttackPackageEvent(event) && event.visible !== false);
}

function exportEvent(context: ExportContext, event: AttackEvent): void {
  switch (event.kind) {
    case "spawn_bullet":
      exportMotionBuffer(context, event, event, [event.polarTheta], { repeatCount: 1, interval: 0, isLaser: isLaserMotion(event) });
      return;
    case "spawn_bullet_spread":
    case "spawn_aimed_spread":
    case "fire_from_moving_origin":
      exportFireClipBuffer(context, event);
      return;
    case "spawn_radial":
      exportRadialBuffer(context, event);
      return;
    case "spawn_curved_laser":
      exportCurvedLaserBuffer(context, event);
      return;
    case "radialBurst":
      exportLegacyRadialBurst(context, event);
      return;
    case "aimedSpread":
      exportLegacyAimedSpread(context, event);
      return;
    case "bossMirroredFan":
      exportLegacyBossFan(context, event);
      return;
    case "polynomialProjectile":
      exportLegacyPolynomial(context, event);
      return;
    case "curvedLaserRing":
      exportLegacyCurvedLaserRing(context, event);
      return;
    case "movingBlock":
      exportMovingBlock(context, event);
      return;
    case "laserBeam":
      exportLaserBeam(context, event);
      return;
    case "rotatingShape":
      exportRotatingShape(context, event);
      return;
    case "warningZone":
      skipEvent(context, event, "warningZone is a non-damaging editor preview and is not exported as a Unity bullet.");
      return;
    case "transform_bullet":
    case "spawn_enemy_origin":
    case "beatPulseRing":
    case "closingWalls":
    case "safeLaneShift":
    case "wallSweep":
      skipEvent(context, event, `${event.kind} is not directly representable as a BulletBuffer yet.`);
      return;
  }

  skipEvent(context, event, "Unsupported event kind.");
}

function exportFireClipBuffer(
  context: ExportContext,
  event: (AttackEvent & BulletMotionFields & FireClipFields) | (AttackEvent & BulletMotionFields & FireClipFields & { aimAtPlayer: number }),
): void {
  const count = Math.max(1, Math.round(event.clipCount));
  const angles: number[] = [];

  for (let index = 0; index < count; index += 1) {
    angles.push(event.polarTheta + event.baseAngleDeg + (index - (count - 1) / 2) * event.angleStepDeg);
  }

  exportMotionBuffer(context, event, event, angles, {
    repeatCount: Math.max(1, Math.round(event.clipRepeat)),
    interval: Math.max(0, event.clipInterval),
    homing: Number(event.aimAtPlayer ?? 0) > 0,
    isLaser: isLaserMotion(event),
  });
}

function exportRadialBuffer(context: ExportContext, event: SpawnRadialEvent): void {
  const count = Math.max(1, Math.round(event.radialCount));
  const angles: number[] = [];

  for (let index = 0; index < count; index += 1) {
    angles.push(event.polarTheta + event.radialStartAngle + (360 / count) * index);
  }

  exportMotionBuffer(context, event, event, angles, {
    repeatCount: Math.max(1, Math.round(event.radialRepeat)),
    interval: Math.max(0, event.radialInterval),
    homing: Number(event.aimAtPlayer ?? 0) > 0,
    isLaser: isLaserMotion(event),
  });
}

function exportCurvedLaserBuffer(context: ExportContext, event: SpawnCurvedLaserEvent): void {
  const count = Math.max(1, Math.round(event.laserCount));
  const angles: number[] = [];

  for (let index = 0; index < count; index += 1) {
    angles.push(event.polarTheta + event.laserAngleStepDeg * index);
  }

  exportMotionBuffer(context, event, event, angles, {
    repeatCount: 1,
    interval: 0,
    isLaser: true,
    laserLength: event.laserLength,
    laserWidth: event.laserWidth,
  });
}

function exportLegacyRadialBurst(context: ExportContext, event: RadialBurstEvent): void {
  const count = Math.max(1, Math.round(event.bulletCount));
  const fullCircle = Math.abs(event.arcDegrees) >= 360;
  const step = fullCircle || count === 1 ? event.arcDegrees / count : event.arcDegrees / (count - 1);
  const angles = Array.from({ length: count }, (_, index) => event.startAngle + step * index);
  const motion = legacyMotion(context.pattern.stage, event.x, event.y, event.bulletSpeed, event.bulletRadius, event.color, event.duration);

  exportMotionBuffer(context, event, motion, angles, {
    repeatCount: Math.max(1, Math.round(event.repeatCount)),
    interval: Math.max(0, event.repeatInterval),
  });
}

function exportLegacyAimedSpread(context: ExportContext, event: AimedSpreadEvent): void {
  const count = Math.max(1, Math.round(event.wayCount));
  const step = count === 1 ? 0 : event.spreadDegrees / (count - 1);
  const baseAngle = radiansToDegrees(Math.atan2(event.targetY - event.y, event.targetX - event.x)) + event.aimOffsetDegrees;
  const angles = Array.from({ length: count }, (_, index) => baseAngle - event.spreadDegrees / 2 + step * index);
  const motion = legacyMotion(context.pattern.stage, event.x, event.y, event.bulletSpeed, event.bulletRadius, event.color, event.duration);

  exportMotionBuffer(context, event, motion, angles, {
    repeatCount: Math.max(1, Math.round(event.fireCount)),
    interval: Math.max(0, event.fireInterval),
    homing: true,
  });
}

function exportLegacyBossFan(context: ExportContext, event: BossMirroredFanEvent): void {
  const angles: number[] = [];
  const baseAngle = radiansToDegrees(Math.atan2(event.targetY - event.y, event.targetX - event.x));
  const angleCount = Math.max(1, Math.round(event.angleCount));
  const speedLayers = Math.max(1, Math.round(event.speedLayers));

  for (let angleIndex = 0; angleIndex < angleCount; angleIndex += 1) {
    for (let speedIndex = 0; speedIndex < speedLayers; speedIndex += 1) {
      void speedIndex;
      angles.push(baseAngle + event.angleStepDegrees * angleIndex - event.angleOffsetDegrees);
    }
  }

  const motion = legacyMotion(context.pattern.stage, event.x, event.y, event.minSpeed, event.bulletRadius, event.color, event.duration);
  const bufferName = createBufferName(context, event);
  const bullets = angles.map((angle, index) => {
    const layer = index % speedLayers;
    return createUnityBulletData(context, motion, angle, {
      speed: event.minSpeed + event.speedStep * layer,
      size: event.bulletRadius,
      life: event.duration,
    });
  });

  addBufferAndSpawner(context, event, bufferName, bullets, {
    repeatCount: Math.max(1, Math.round(event.fireCount)),
    interval: Math.max(0, event.fireInterval),
    pos: toUnityPoint(context, event.x, event.y),
    color: colorToFloat4(event.color),
    homing: true,
  });
}

function exportLegacyPolynomial(context: ExportContext, event: PolynomialProjectileEvent): void {
  const count = Math.max(1, Math.round(event.bulletCount));
  const fullCircle = Math.abs(event.spreadDegrees) >= 360;
  const step = fullCircle || count === 1 ? event.spreadDegrees / count : event.spreadDegrees / (count - 1);
  const angles = Array.from({ length: count }, (_, index) => event.startAngle + step * index);
  const motion = legacyMotion(context.pattern.stage, event.x, event.y, event.bulletSpeed, event.bulletRadius, event.color, event.duration);

  motion.originVx = event.originVx;
  motion.originVy = event.originVy;
  motion.polynomialA = event.curveA / polynomialUnitPixels;
  motion.polynomialB = event.curveB / polynomialUnitPixels;
  motion.polarThetaVelocity = event.thetaVelocity;
  motion.gravity = event.gravity;

  exportMotionBuffer(context, event, motion, angles, {
    repeatCount: Math.max(1, Math.round(event.fireCount)),
    interval: Math.max(0, event.fireInterval),
  });
}

function exportLegacyCurvedLaserRing(context: ExportContext, event: CurvedLaserRingEvent): void {
  const count = Math.max(1, Math.round(event.laserCount));
  const angles = Array.from({ length: count }, (_, index) => event.startAngle + (360 / count) * index);
  const motion = legacyMotion(context.pattern.stage, event.x, event.y, event.extendSpeed, event.width, event.color, event.duration);

  motion.polynomialA = event.curveA / polynomialUnitPixels;
  motion.polynomialB = event.curveB / polynomialUnitPixels;
  motion.polarThetaVelocity = event.rotationSpeed;
  motion.typeId = 4;
  motion.visualWidth = event.length;
  motion.visualHeight = event.width;

  exportMotionBuffer(context, event, motion, angles, {
    repeatCount: 1,
    interval: 0,
    isLaser: true,
    laserLength: event.length,
    laserWidth: event.width,
  });
}

function exportMovingBlock(context: ExportContext, event: MovingBlockEvent): void {
  const dx = event.endX - event.startX;
  const dy = event.endY - event.startY;
  const distance = Math.hypot(dx, dy);
  const speed = event.duration > 0 ? distance / event.duration : 0;
  const angle = distance > 0 ? radiansToDegrees(Math.atan2(dy, dx)) : event.rotationStart;
  const size = event.shape === "circle" ? event.radius * 2 : Math.max(event.width, event.height);
  const motion = legacyMotion(context.pattern.stage, event.startX, event.startY, speed, size, event.color, event.duration);

  motion.typeId = event.shape === "circle" ? 0 : 2;
  motion.visualWidth = event.width;
  motion.visualHeight = event.height;
  motion.visualAngle = event.rotationStart;
  motion.angleSpeed = event.rotationSpeed;

  exportMotionBuffer(context, event, motion, [angle], {
    repeatCount: 1,
    interval: 0,
  });
}

function exportLaserBeam(context: ExportContext, event: LaserBeamEvent): void {
  const motion = legacyMotion(context.pattern.stage, event.x, event.y, 0, event.width, event.color, event.duration);

  motion.typeId = 4;
  motion.visualWidth = event.length;
  motion.visualHeight = event.width;
  exportMotionBuffer(context, event, motion, [event.angle], {
    repeatCount: 1,
    interval: 0,
    isLaser: true,
    laserLength: event.length,
    laserWidth: event.width,
  });
}

function exportRotatingShape(context: ExportContext, event: RotatingShapeEvent): void {
  const motion = legacyMotion(context.pattern.stage, event.x, event.y, 0, event.size, event.color, event.duration);

  motion.typeId = event.sides === 4 ? 2 : 0;
  motion.polarRadius = event.orbitRadius / Math.max(1, event.size);
  motion.polarThetaVelocity = event.rotationSpeed;
  motion.visualAngle = event.startAngle;
  exportMotionBuffer(context, event, motion, [event.startAngle], {
    repeatCount: 1,
    interval: 0,
  });
}

function exportMotionBuffer(
  context: ExportContext,
  event: AttackEvent,
  motion: BulletMotionFields & { color: number; duration: number },
  angles: number[],
  options: {
    repeatCount: number;
    interval: number;
    homing?: boolean;
    isLaser?: boolean;
    laserLength?: number;
    laserWidth?: number;
  },
): void {
  const bufferName = createBufferName(context, event);
  const bullets = angles.map((angle) => createUnityBulletData(context, motion, angle));

  addBufferAndSpawner(context, event, bufferName, bullets, {
    repeatCount: options.repeatCount,
    interval: options.interval,
    pos: getMotionOrigin(context, motion),
    originVlc: toUnityVector(context, motion.originVx, motion.originVy),
    color: colorToFloat4(event.color),
    homing: options.homing ?? false,
    isLaser: options.isLaser ?? false,
    laserLength: options.laserLength,
    laserWidth: options.laserWidth,
  });
}

function addBufferAndSpawner(
  context: ExportContext,
  event: AttackEvent,
  bufferName: string,
  bullets: UnityBulletDataJson[],
  options: {
    repeatCount: number;
    interval: number;
    pos: Float2;
    originVlc?: Float2;
    color: Float4;
    homing?: boolean;
    isLaser?: boolean;
    laserLength?: number;
    laserWidth?: number;
  },
): void {
  const laserLength = options.isLaser
    ? Math.max(getUnityOverscanLaserLength(), options.laserLength ? toUnityScalar(context, options.laserLength) : 0)
    : 0;

  context.buffers.push({
    name: bufferName,
    bullets,
    homing: options.homing ?? false,
    isLaser: options.isLaser ?? false,
  });

  context.spawners.push({
    clipName: bufferName,
    count: Math.max(1, Math.round(options.repeatCount)),
    interval: round(options.interval),
    time: round(Math.max(0, event.startTime)),
    pos: options.pos,
    originVlc: options.originVlc ?? float2(0, 0),
    angle: 0,
    angleInterval: 0,
    color: options.color,
    speed: 0,
    size: 0,
    laserCount: options.isLaser ? 1 : 0,
    laserSpacing: 0,
    laserLength,
    laserWidth: options.laserWidth ? toUnityScalar(context, options.laserWidth) : 0,
  });
}

function createUnityBulletData(
  context: ExportContext,
  motion: BulletMotionFields & { color: number; duration: number },
  editorAngleDegrees: number,
  overrides: { speed?: number; size?: number; life?: number } = {},
): UnityBulletDataJson {
  const editorTypeId = Math.round(motion.typeId ?? 0);
  const typeId = toUnityBulletTypeId(editorTypeId);
  const speed = toUnitySpeed(context, overrides.speed ?? motion.pathSpeed, editorAngleDegrees);
  const size = editorTypeId === 4 ? getUnityOverscanLaserLength() : toUnityScalar(context, overrides.size ?? getMotionSize(motion));
  const startX = toUnityScalarX(context, motion.pathStartX);
  const xUnitScale = polynomialUnitPixels / context.scaleX;
  const yUnitScale = polynomialUnitPixels / context.scaleY;
  const polynomial = {
    x: round((-motion.polynomialA * yUnitScale) / xUnitScale),
    y: round((-motion.polynomialB * yUnitScale) / (xUnitScale * xUnitScale)),
    z: round((-motion.polynomialC * yUnitScale) / (xUnitScale * xUnitScale * xUnitScale)),
    w: round((-motion.polynomialD * yUnitScale) / (xUnitScale * xUnitScale * xUnitScale * xUnitScale)),
  };
  const angle = toUnityAngle(context, editorAngleDegrees);
  const startPos = float2(startX, evaluateUnityPolynomial(polynomial, startX));
  const data: UnityBulletDataJson = {
    position: float2(0, 0),
    velocity: float2(0, 0),
    angle: 0,
    originPos: float2(0, 0),
    originVlc: float2(0, 0),
    startX,
    speed,
    accel: 0,
    acccel: 0,
    gravity: round(-motion.gravity / context.scaleY),
    angleSpeed: round(degreesToRadians(-motion.angleSpeed)),
    polarForm: float2(round(motion.polarRadius), round(degreesToRadians(angle))),
    radiusVlc: round(motion.polarRadiusVelocity),
    thetaVlc: round(degreesToRadians(-motion.polarThetaVelocity)),
    startPos,
    nowCalculateVlc: float2(0, 0),
    nowCalculateX: startX,
    polynomial,
    typeId,
    typeName: typeNameFromTypeId(editorTypeId),
    size,
    color: colorToFloat4(motion.color),
    areaNum: 0,
    time: 0,
    appearTime: 0,
    life: round(overrides.life ?? motion.duration),
    random: 0,
    isActive: true,
  };

  data.nowCalculateVlc = getInitialPolynomialVelocity(data.polynomial, data.startX, speed);
  return data;
}

function legacyMotion(stage: StageSize, x: number, y: number, speed: number, size: number, color: number, duration: number): BulletMotionFields & { duration: number; color: number } {
  return {
    originX: x,
    originY: y,
    originVx: 0,
    originVy: 0,
    polynomialA: 0,
    polynomialB: 0,
    polynomialC: 0,
    polynomialD: 0,
    pathStartX: 0,
    pathSpeed: speed,
    polarRadius: 1,
    polarRadiusVelocity: 0,
    polarTheta: 0,
    polarThetaVelocity: 0,
    gravity: 0,
    angleSpeed: 0,
    typeId: 0,
    visualSize: size,
    visualPreset: "bullet",
    visualWidth: size,
    visualHeight: size,
    visualAngle: 0,
    duration,
    color,
  };
}

function getMotionOrigin(context: ExportContext, event: BulletMotionFields): Float2 {
  return toUnityPoint(context, event.originX, event.originY);
}

function getMotionSize(event: BulletMotionFields): number {
  const typeId = Math.round(event.typeId ?? 0);

  if (typeId === 4) {
    return event.visualWidth;
  }

  if (typeId !== 0) {
    return Math.max(event.visualWidth, event.visualHeight);
  }

  return event.visualSize;
}

function isLaserMotion(event: BulletMotionFields): boolean {
  return Math.round(event.typeId ?? 0) === 4;
}

function createBufferName(context: ExportContext, event: AttackEvent): string {
  const baseName = sanitizeUnityName(event.name || event.kind || "clip");
  let nextName = baseName;
  let index = 1;

  while (context.usedNames.has(nextName)) {
    index += 1;
    nextName = `${baseName}_${index}`;
  }

  context.usedNames.add(nextName);
  return nextName;
}

function sanitizeUnityName(name: string): string {
  const normalized = name.trim().replace(/\s+/g, "_").replace(/[^\p{L}\p{N}_-]+/gu, "");

  return normalized || "clip";
}

function skipEvent(context: ExportContext, event: AttackEvent, reason: string): void {
  context.skippedEvents.push({
    id: event.id,
    name: event.name,
    kind: event.kind,
    reason,
  });
}

function getMeasureDuration(pattern: BulletPattern): number {
  const bpm = Math.max(1, pattern.timeline.bpm);
  const beats = Math.max(1, pattern.timeline.beatsPerMeasure);

  return (60 / bpm) * beats;
}

function toUnityPoint(context: ExportContext, x: number, y: number): Float2 {
  return float2(x / context.scaleX, (context.pattern.stage.height - y) / context.scaleY);
}

function toUnityVector(context: ExportContext, x: number, y: number): Float2 {
  return float2(x / context.scaleX, -y / context.scaleY);
}

function toUnityScalar(context: ExportContext, value: number): number {
  return round(value / ((context.scaleX + context.scaleY) / 2));
}

function toUnityScalarX(context: ExportContext, value: number): number {
  return round(value / context.scaleX);
}

function toUnityDistanceAlongAngle(context: ExportContext, value: number, editorAngleDegrees: number): number {
  const angle = degreesToRadians(editorAngleDegrees);
  const x = Math.cos(angle) / context.scaleX;
  const y = -Math.sin(angle) / context.scaleY;

  return round(value * Math.hypot(x, y));
}

function getUnityOverscanLaserLength(): number {
  return round(Math.hypot(unityWorldWidth, unityWorldHeight) * unityLaserOverscanMultiplier);
}

function toUnitySpeed(context: ExportContext, value: number, editorAngleDegrees: number): number {
  return toUnityDistanceAlongAngle(context, value, editorAngleDegrees);
}

function toUnityAngle(context: ExportContext, editorAngleDegrees: number): number {
  const angle = degreesToRadians(editorAngleDegrees);

  return radiansToDegrees(Math.atan2(-Math.sin(angle) / context.scaleY, Math.cos(angle) / context.scaleX));
}

function colorToFloat4(color: number): Float4 {
  return {
    x: round(((color >> 16) & 0xff) / 255),
    y: round(((color >> 8) & 0xff) / 255),
    z: round((color & 0xff) / 255),
    w: 1,
  };
}

function toUnityBulletTypeId(editorTypeId: number): number {
  if (editorTypeId === 0) {
    return 1;
  }

  return editorTypeId;
}

function typeNameFromTypeId(typeId: number): string {
  switch (typeId) {
    case 1:
      return "normal";
    case 2:
      return "box";
    case 3:
      return "diamond";
    case 4:
      return "laser";
    case 0:
    default:
      return "normal";
  }
}

function getInitialPolynomialVelocity(polynomial: Float4, x: number, speed: number): Float2 {
  const tangent = polynomial.x + 2 * polynomial.y * x + 3 * polynomial.z * x * x + 4 * polynomial.w * x * x * x;
  const magnitude = Math.sqrt(1 + tangent * tangent) || 1;

  return float2(speed / magnitude, (tangent * speed) / magnitude);
}

function evaluateUnityPolynomial(polynomial: Float4, x: number): number {
  return round(polynomial.x * x + polynomial.y * x * x + polynomial.z * x * x * x + polynomial.w * x * x * x * x);
}

function float2(x: number, y: number): Float2 {
  return { x: round(x), y: round(y) };
}

function degreesToRadians(degrees: number): number {
  return (degrees * Math.PI) / 180;
}

function radiansToDegrees(radians: number): number {
  return (radians * 180) / Math.PI;
}

function round(value: number): number {
  return Number((Number.isFinite(value) ? value : 0).toFixed(5));
}
